services:
  opensips-cp:
    image: eriklee1895/opensips-cp:9.3.2
    build: .
    container_name: opensips-cp
    ports:
      - 5180:80
    environment:
      DB_HOST: 192.168.1.100
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: opensips
